### ISSUE TITLE
Social api duplication

### ISSUE THREAD

**Issue by vsellier** [exo-addons/lecko#5]
The plugin seems to redeclare the same api endpoints as the social api (included the endpoint dedicated to creations/deletion and update). Is these really needed ? 
IMO this is blocker.

for example, there no significant diff between the social and lecko addons ActivityRestResourcesV1.java file :

```
2c2
<  * Copyright (C) 2003-2016 eXo Platform SAS.
---
>  * Copyright (C) 2003-2014 eXo Platform SAS.
4c4,7
<  * This file is part of Lecko Analytics Add-on - Service.
---
>  * This program is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU Affero General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or
>  * (at your option) any later version.
6,11c9
<  * Lecko Analytics Add-on - Service is free software; you can redistribute it and/or modify it
<  * under the terms of the GNU Lesser General Public License as
<  * published by the Free Software Foundation; either version 3 of
<  * the License, or (at your option) any later version.
<  *
<  * Lecko Analytics Add-on - Service software is distributed in the hope that it will be useful,
---
>  * This program is distributed in the hope that it will be useful,
13,14c11,12
<  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
<  * Lesser General Public License for more details.
---
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU Affero General Public License for more details.
16,19c14,15
<  * You should have received a copy of the GNU Lesser General Public
<  * License along with Lecko Analytics Add-on - Service; if not, write to the Free
<  * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
<  * 02110-1301 USA, or see <http://www.gnu.org/licenses/>.
---
>  * You should have received a copy of the GNU Affero General Public License
>  * along with this program. If not, see <http://www.gnu.org/licenses/>.
21c17
< package org.exoplatform.addons.lecko.social.rest.impl.activity;
---
> package org.exoplatform.social.rest.impl.activity;
48d43
< import org.exoplatform.addons.lecko.social.rest.api.EntityBuilder;
60a56
> import org.exoplatform.social.rest.api.EntityBuilder;
```

**Comment by rdenarie** [comment]
In fact, the aim of this override is be able to get all elements (all spaces for example if user is in the correct group, define by exo.api-access.group=api-access  in exo.properties).

If I use the default version of theses service, I get only space in which api user is.

Now, I guess we can improve this : 
- make theses services called only by lecko (rename it). It will prevent the platform to use the modified version 
- make theses services as child class of default one, to override only the necessary part.
WDYT

**Comment by thomasdelhomenie** [comment]
I agree we should rename the REST endpoints changed for Lecko. It would avoid confusion and errors.
You can extend the default services, or even create a new class which calls the default services when necessary.

**Comment by plamarque** [comment]
These should be features of the regular API... Hope to retrofit these capabilities some day.

**Comment by rdenarie** [comment]
Hello.
I just commit a fix for this issue on the [branche](https://github.com/exo-addons/lecko/tree/fix/remove-webservice)
This idea is to completly remove the api override, and remove the webservice usage, just use java services to get spaces, users, streams, activities, comments and likes.

@vsellier @thomasdelhomenie Please take a look on the branch.
I wish to know if there was a good reason to do like this before making the merge. We are waiting for Aymen and Ahmed point of view.

Thanks

**Comment by rdenarie** [comment]
Unit tests added
Branche merged
