### ISSUE TITLE
Exception during dump generation is lost

### ISSUE THREAD

**Issue by vsellier** [exo-addons/lecko#7]
in [LeckoRestService.java](https://github.com/exo-addons/lecko/blob/master/service/src/main/java/org/exoplatform/addons/lecko/rest/LeckoRestService.java#L63), if an exception occurs during the dump generation, the exception detail is lost :

`2017-03-06 14:45:52,359 | ERROR | null [o.e.addons.lecko.rest.LeckoRestService<LeckoDumpService>]`

**Comment by rdenarie** [comment]
Class removed
